# Docker
trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e3b9ad4a-0e73-4d36-937e-22329ed1eec5'
  imageRepository: 'jeecbrain'
  containerRegistry: 'neecist.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        arguments: --build-arg SECRET_KEY=$(SECRET_KEY),APP_ENV=$(APP_ENV),APP_DB=$(APP_DB),DATABASE_URL=$(DATABASE_URL),CLIENT_USERNAME=$(CLIENT_USERNAME),CLIENT_KEY=$(CLIENT_KEY),ROCKET_CHAT_ADMIN_PASSWORD=$(ROCKET_CHAT_ADMIN_PASSWORD),JWT_SECRET=$(JWT_SECRET)
    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)
