"""empty message

Revision ID: 30f7d2ff8821
Revises: fecea89d5f92
Create Date: 2022-03-09 14:00:27.789679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f7d2ff8821'
down_revision = 'fecea89d5f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_lootbox_winner_id_fkey', 'student_lootbox', type_='foreignkey')
    op.create_foreign_key(None, 'student_lootbox', 'students', ['winner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_lootbox', type_='foreignkey')
    op.create_foreign_key('student_lootbox_winner_id_fkey', 'student_lootbox', 'students', ['winner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
