"""empty message

Revision ID: 5d1695f4c3c7
Revises: 
Create Date: 2022-03-07 22:23:00.300728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1695f4c3c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lootbox_rewards', sa.Column('lootboxes_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lootbox_rewards', 'lootboxes', ['lootboxes_id'], ['id'], ondelete='SET NULL')
    op.drop_column('lootbox_rewards', 'repeatable')
    op.drop_column('lootbox_rewards', 'active')
    op.drop_column('lootbox_rewards', 'name')
    op.add_column('student_lootbox', sa.Column('lootbox_rewards_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student_lootbox', 'lootbox_rewards', ['lootbox_rewards_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_lootbox', type_='foreignkey')
    op.drop_column('student_lootbox', 'lootbox_rewards_id')
    op.add_column('lootbox_rewards', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('lootbox_rewards', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lootbox_rewards', sa.Column('repeatable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lootbox_rewards', type_='foreignkey')
    op.drop_column('lootbox_rewards', 'lootboxes_id')
    # ### end Alembic commands ###
