"""empty message

Revision ID: 88b36107b7e6
Revises: 30f7d2ff8821
Create Date: 2022-03-11 11:15:59.257531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b36107b7e6'
down_revision = '30f7d2ff8821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_lootbox', sa.Column('reward_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_lootbox', 'rewards', ['reward_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_lootbox', type_='foreignkey')
    op.drop_column('student_lootbox', 'reward_id')
    # ### end Alembic commands ###
