"""empty message

Revision ID: b95f58c31c87
Revises: 
Create Date: 2022-02-23 19:28:00.940787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95f58c31c87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('show_prizes', sa.Boolean(), nullable=True))
    op.add_column('jeecpot_rewards', sa.Column('cv_platform_raffle_reward_id', sa.Integer(), nullable=True))
    op.add_column('jeecpot_rewards', sa.Column('cv_platform_raffle_winner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jeecpot_rewards', 'students', ['cv_platform_raffle_winner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'jeecpot_rewards', 'rewards', ['cv_platform_raffle_reward_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jeecpot_rewards', type_='foreignkey')
    op.drop_constraint(None, 'jeecpot_rewards', type_='foreignkey')
    op.drop_column('jeecpot_rewards', 'cv_platform_raffle_winner_id')
    op.drop_column('jeecpot_rewards', 'cv_platform_raffle_reward_id')
    op.drop_column('events', 'show_prizes')
    # ### end Alembic commands ###
